secret_token: <%= ENV['SECRET_TOKEN'] %>

twitter_key: <%= ENV['TWITTER_KEY'] %>
twitter_secret: <%= ENV['TWITTER_SECRET'] %>

facebook_app_id: <%= ENV['FACEBOOK_APP_ID'] %>
facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>
